import Head from 'next/head'
import React, { useState } from 'react'
import Logo from '../../../public/icons/Logo-16.png'
import Notifications, { notificationItems } from '@/components/ui/settings/Notifications';
import History from '@/components/ui/settings/History';

const sidebarLinks = [
  { id: 1, title: "Notifications", url: "#notifications" },
  { id: 2, title: "History", url: "#history" },
  { id: 3, title: "Reset", url: "#reset" },
];


function Settings() {
  const [activeLinkId, setActiveLinkId] = useState(null)
  const [loading, setLoading] = useState(false)
  const [history, setHistory] = useState([]);
  const [notificationStates, setNotificationStates] = useState({});


  const handleLinkClick = (linkId) => {
    setActiveLinkId(linkId);
  };

  const clearHistory = () => {
    chrome.history.deleteAll(() => {
      setHistory([]);
      chrome.storage.sync.remove("visitedSites");
    });
  };

  const resetSettings = () => {
    //  write the logic to reset notificatiion
    setLoading(true);
    setTimeout(() => {
      setLoading(false);

    }, 2000);
    setNotificationStates(false);
    chrome.storage.sync.set({ notificationStates: false });

    console.log("reset values");
  }

  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Chrome settings page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen overflow-x-hidden grid grid-cols-10 items-start justify-items-stretch scroll-smooth">
        {/* sidebar */}
        <aside className="w-full col-span-2 pt-[20%] h-screen border-r  relative">
          <div className="w-full fixed px-4">
            <div className="w-full flex items-center justify-start space-x-1">
              <span
                className="w-[2rem] aspect-square "
                style={{
                  background: `url(${Logo.src}) center center/contain no-repeat`,
                }}
              ></span>
              <span className="text-center font-bold text-[#2d2964] font-sans text-[1.4rem]">
                BlockBait
              </span>
            </div>
            <ul className="w-full flex flex-col space-y-3 text-[1rem] mt-[5%] mx-2">
              {sidebarLinks.map((link) => (
                <li
                  key={link.id}
                  className={activeLinkId === link.id ? "w-full py-2 px-4 rounded bg-[#2d2964] text-white" : "w-full py-2 px-4 rounded hover:bg-[#2d2964] hover:text-white"}
                >
                  <a
                    onClick={() => handleLinkClick(link.id)}
                    href={link.url} >{link.title}</a>
                </li>
              ))}
            </ul>
          </div>
        </aside>
        {/* main section of the dashboard  */}
        <section className="w-full h-full col-span-8 bg-[#E6E9F3] px-16 relative">
          <div className="w-full flex flex-col items-start space-y-2 mt-[5%] inset-x-0">
            <h3 className="text-[1.6rem] font-bold">Settings</h3>
            <p className="text-[1rem] text-black/60">Manage your preferences here</p>
          </div>

          {/* notifications */}
          <div id="notifications" className="my-4 pt-[10%]">
            <h5 className='text-[1.1rem] font-semibold my-4'>Notifications</h5>
            {/* <Notifications /> */}
            <Notifications
              notificationStates={notificationStates}
              setNotificationStates={setNotificationStates}
            />
          </div>

          {/* history */}
          <div id="history" className="my-[10%] pt-[10%]">
            <h5 className='text-[1.1rem] font-semibold my-2'>History</h5>
            <p className='text-[0.9rem] my-2'>All Activities that has been perfomed with Blockbait</p>
            <History history={history} setHistory={setHistory} />
          </div>

          {/* reset */}
          <div id="reset" className="my-[10%] pt-[10%]">
            <h5 className='text-[1.1rem] font-semibold my-4'>Reset</h5>
            <p className='text-[0.9rem] my-2'>This clears data history and returns blockbait to default settings</p>
            <div className='flex items-center space-x-8'>
              <button className='px-6 py-3 rounded border-2 border-[#4E46B4]  text-[0.8rem] ' role='button' onClick={clearHistory}> Delete history</button>
              <button className='px-6 py-3 rounded border-2  border-[#4E46B4] bg-[#4E46B4] text-[0.8rem] text-white' role='button' onClick={resetSettings}>{loading ? <div className="w-4 aspect-square mx-auto border-4 border-dotted rounded-full animate-spin border-white"></div> : "Reset"}</button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

export default Settings;
